version: '3'

volumes:
  food_data:
  food_media:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - food_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - food_media:/app/media
    depends_on:
      - db
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend
  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static
      - food_media:/media
    depends_on:
      - frontend
