# Generated by Django 4.2.10 on 2024-03-04 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipeingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-id', 'name', 'author'), 'verbose_name': 'рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
